add first component
deadmagic161/movie-searcher pull request #1
Opened 2020-01-23 16:00 UTC by deadmagic161

Добавил первые компоненты которые берут данные из готового json
Над дизайном пока не думал

2020-01-26 10:43 UTC, Geschoss requested changes

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-list/movie-list.tsx
> +    const [films, setFilms] = useState<MovieItemProps[]>([]);
Все же везде `movie`  давай и тут тоже сделаем `movie`

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-list/movie-list.tsx
> +            const data = response;
Лишняя переменная, можешь же сразу setMovies(response)

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-list/movie-list.tsx
> +        fetch('https://devlab.website/v1/movies')
Давай вынесем эту url в переменную
const MOVIES_URL = 'https://devlab.website/v1/movies'
Старайся подобные вещи сразу выносить в константы.
Создай файл constants.ts и пусть там хранятся все константы.

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-list/movie-list.tsx
> +        <div className='movie-list__wrapper'>
что бы не было вот какой лишней инфы в классах `movie-list__wrapper` типа мы и так в комопненте `MovieList` нам нужно еще и `movie-list` писать. Посмотри css modules. очень крутая штука

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-item/movie-item.tsx
> +                {isFavorite ? `Убрать из избранного` : `В избранное`}
Тоже можно в константы

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-item/movie-item.tsx
> +export const MovieItem = (props: MovieItemProps) => {
Можешь еше про memo почитать.

2020-01-26 10:43 UTC, Geschoss commented on src/components/movie-item/movie-item.tsx
> +    const [isFavorite, setFavorite] = useState(false);
Для эксперемента можешь попробовать вынести этот стейт в компонент выше. Но придется менять логику

2020-01-26 10:43 UTC, Geschoss commented on src/App.tsx
> -import './App.css';
Стили где то потерял=(

2020-01-30 15:37 UTC, deadmagic161 commented on src/components/movie-list/movie-list.tsx
> +    const [films, setFilms] = useState<MovieItemProps[]>([]);
done

2020-01-30 15:37 UTC, deadmagic161 commented on src/components/movie-list/movie-list.tsx
> +            const data = response;
done

2020-01-30 15:38 UTC, deadmagic161 commented on src/components/movie-list/movie-list.tsx
> +        fetch('https://devlab.website/v1/movies')
вынес просто урл, остальное буду просто приписывать по типу MOVIE_URL + 'movies'

2020-01-30 15:38 UTC, deadmagic161 commented on src/components/movie-list/movie-list.tsx
> +        <div className='movie-list__wrapper'>
Сейчас появился макет,начну прикручивать какой нибудь ui

2020-01-30 15:39 UTC, deadmagic161 commented on src/components/movie-item/movie-item.tsx
> +                {isFavorite ? `Убрать из избранного` : `В избранное`}
По макету вижу что будет иконка,будет меняться заливка в зависимости от стейта

2020-01-30 15:39 UTC, deadmagic161 commented on src/components/movie-item/movie-item.tsx
> +export const MovieItem = (props: MovieItemProps) => {
Прочту

2020-01-30 15:40 UTC, deadmagic161 commented on src/components/movie-item/movie-item.tsx
> +    const [isFavorite, setFavorite] = useState(false);
Но как я понял будет перерендер списка каждый раз,это вроде не очень хорошо

2020-01-30 15:40 UTC, deadmagic161 commented on src/App.tsx
> -import './App.css';
Удалил)

2020-02-01 10:41 UTC, Geschoss approved these changes

2020-02-02 15:42 UTC, kirzharov commented
Можно смержить 👍

2020-02-03 14:08 UTC, merged